FROM registry.access.redhat.com/ubi7/ubi

MAINTAINER Eric Löffler <eloeffler@aservo.com>

ADD ca_certs/ /usr/share/pki/ca-trust-source/anchors/
ADD target/dist/ /app/lib/
ADD init.sh /app/
ADD start.sh /app/

RUN chmod -R 644 /usr/share/pki/ca-trust-source/anchors/ && \
    groupadd -r -g 1000 appuser && \
    useradd -r -g 1000 -u 1000 appuser && \
    chown -R appuser:appuser /app

RUN yum makecache && \
    yum -y update && \
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm  && \
    yum -y install \
        ca-certificates \
        openssl \
        nc \
        jq \
        java-11-openjdk-headless \
        && \
    yum clean all && \
    rm -rf /tmp/* /var/tmp/*

RUN update-ca-trust

WORKDIR /app

USER appuser

ENTRYPOINT ["/app/init.sh"]

CMD ["/app/start.sh"]
