FROM registry.access.redhat.com/ubi8/ubi

MAINTAINER Eric Löffler <eloeffler@aservo.com>

ARG UID=1000
ARG GID=1000

RUN yum makecache && \
    yum -y update && \
    yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm  && \
    yum -y install \
        ca-certificates \
        java-11-openjdk-headless \
        openssl \
        nc \
        jq \
        && \
    yum clean all && \
    rm -rf /tmp/* /var/tmp/*

ADD docker/docker-entrypoint.sh /opt/app/
ADD docker/docker-start.sh /opt/app/
ADD target/dist/ /opt/app/lib/

RUN groupadd -r -g "$GID" appuser && \
    useradd -r -g "$GID" -u "$UID" appuser && \
    chown -R appuser:appuser /opt/app

USER appuser

WORKDIR /opt/app

ENTRYPOINT ["/opt/app/docker-entrypoint.sh"]

CMD ["/opt/app/docker-start.sh"]
